// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'operationBar': string;
  'sentenceItem': string;
  'table': string;
}
export const cssExports: CssExports;
export default cssExports;
